dtracking/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^movil/tipos_gestion/$', tipos_gestion,
        name='tipos_gestion'),
    url(r'^movil/gestiones/$', gestiones_pendientes,
        name='gestiones_pendientes'),
    url(r'^movil/login/$', movil_login,
        name='dtracking_login'),
    url(r'^movil/cargar_gestion/$', cargar_gestion,
        name='cargar_gestion'),
    url(r'^movil/cargar_media/$', cargar_media,
        name='cargar_media'),
    url(r'^movil/agregar_registro/$', agregar_registro,
        name='agregar_registro'),
    url(r'^barrios_huerfanos/', barrios_huerfanos.as_view(),
        name='barrios_huerfanos'),
    url(r'^movil/seguimiento_gps/', seguimiento_gps,
        name='seguimiento_gps'),
    url(r'^movil/mensajeria/', mensajeria,
        name='mensajeria_movil'),
    url(r'^view_details/', view_details,
        name='view_details'),
    url(r'^edicion_elementos/', edicion_elementos,
        name='edicion_elementos'),
    url(r'^guardar_elementos/', guardar_elementos,
        name='guardar_elementos'),
    url(r'^get_log_gestion/', get_log_gestion,
        name='get_log_gestion'),
    url(r'^asignar_gestion/', asignar_gestion,
        name='asignar_gestion'),
    url(r'^examen_previo/', examen_previo,
        name='examen_previo'),
    url(r'^get_municipios/', get_municipios,
        name='get_municipios'),
    url(r'^get_barrios/', get_barrios,
        name='get_barrios'),
    url(r'^get_usos_gestion/', get_usos_gestion,
        name='get_usos_gestion'),
    url(r'^get_avaluos_posicion/', get_avaluo_mes_posiciones,
        name='get_avaluos_posicion'),
    url(r'^gestion_adjuntos/', gestion_adjuntos.as_view(),
        name='gestion_adjuntos'),
    url(r'^gestion_borrar_adjunto/', gestion_borrar_adjunto,
        name='gestion_borrar_adjunto'),
    url(r'^gestion_proforma/', generar_proforma,
        name='gestion_proforma'),
    url(r'^generar_asignacion/', generar_asignacion,
        name='generar_asignacion'),
    url(r'^peritaje/', peritaje.as_view(),
        name='peritaje'),
    url(r'^reporte/', reporte,
        name='reporte'),
    url(r'^operaciones/', operaciones.as_view(),
        name='operaciones'),
    url(r'^control/', control.as_view(),
        name='control'),
    url(r'^gerencia/', gerencia.as_view(),
        name='gerencia'),
]

valuarte/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from home.views import index

urlpatterns = [
    url(r'^$', index, name="valuarte_index"),
    url(r'^admin/', admin.site.urls, name="admin"),
    url(r'^admin/ajax/', include('base.ajax_urls')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^dtracking/', include('dtracking.urls')),
]

base/models.py
from __future__ import unicode_literals

from django.db import models
from django.db.models import Max
from django.forms.models import model_to_dict


def get_code(entidad, length=4):
        model = type(entidad)
        code = ''
        sets = model.objects.filter(code__isnull=False)
        if sets:
            maxi = str(sets.aggregate(Max('code'))['code__max'])
            if maxi:
                consecutivo = list(range(1, int(maxi)))
                ocupados = list(sets.values_list('code', flat=True))
                n = 0
                for l in ocupados:
                    ocupados[n] = int(str(l))
                    n += 1
                disponibles = list(set(consecutivo) - set(ocupados))
                if len(disponibles) > 0:
                    code = min(disponibles)
                else:
                    code = max(ocupados) + 1
        else:
            code = 1
        return str(code).zfill(length)


class base(models.Model):

    def __iter__(self):
        for field_name in self._meta.get_all_field_names():
            try:
                value = getattr(self, field_name)
            except:
                value = None
            yield (field_name, value)

    def __getitem__(self, fieldname):
        try:
            return getattr(self, fieldname)
        except:
            return None

    def to_json(self):
        return model_to_dict(self)

    class Meta:
        abstract = True


class base_entidad(base):
    code = models.CharField(max_length=25, null=True, blank=True,
        verbose_name="codigo")
    name = models.CharField(max_length=100, verbose_name="nombre")

    class Meta:
        abstract = True


class Entidad(base_entidad):
    activo = models.BooleanField(default=True)

    def __unicode__(self):
        if self.code and self.name:
            return str(self.code) + " " + self.name
        elif self.name:
            return self.name
        elif self.code:
            return str(self.code)
        else:
            return ''

    @staticmethod
    def autocomplete_search_fields():
        return ("code__iexact", "name__icontains",)

    def save(self, *args, **kwargs):
        if self.code is None or self.code == '':
            self.code = get_code(self)
        super(Entidad, self).save()

    class Meta:
        abstract = True
        ordering = ['name']

dtracking/models.py
# coding=utf-8
from __future__ import unicode_literals

import sys
from django.core.mail import EmailMessage
from django.utils.html import mark_safe
from base.models import Entidad
from django.contrib.auth.models import User
from django.db import models
from geoposition.fields import GeopositionField
from jsonfield import JSONField
import datetime as datetime_base
from datetime import datetime, timedelta, date
import json
from django.utils.encoding import smart_str
from colorfield.fields import ColorField
from django.template.loader import render_to_string
from django.utils import timezone
from django.db.models import Sum
from django.conf import settings
from django.contrib import messages


def add_business_days(origin_date, add_days):
    '''
    Función que añade días hábiles a una fecha.
    '''
    while add_days > 0:
        origin_date += timedelta(days=1)
        weekday = origin_date.weekday()  # regresa un entero de 0 - 6
        if weekday >= 4:  # sunday = 6
            continue
        add_days -= 1
    return origin_date


def diff_business_days(origin_date, end_date):
    days = 0
    while not origin_date > end_date:
        weekday = origin_date.weekday()  # regresa un entero de 0 - 6
        origin_date += timedelta(days=1)  # pasar al siguiente dia
        if weekday >= 4:
            continue
        days += 1
    return days


def ifnull(var, val):
    if var is None:
        return val
    return var


def get_gestor(user):
    try:
        return Gestor.objects.get(user=user)
    except:
        return None


CONECTIONS = (
    ('SMS + WIFI', 'SMS + WIFI'),
    ('3G + WIFI', '3G + WIFI'),
    ('WIFI', 'WIFI'),
)

ESTADOS_LOG_GESTION = (('RECEPCIONADO', 'RECEPCIONADO'),  # 0 0
                       ('ASIGNADO A EVALUADOR', 'ASIGNADO A EVALUADOR'),  # 1 0
                       ('LEVANTAMIENTO REALIZADO', 'LEVANTAMIENTO REALIZADO'),  # 2 0
                       ('CONTROL DE CALIDAD', 'CONTROL DE CALIDAD'),  # 3 0
                       ('EN REVISION FINAL DE INFORME', 'EN REVISION FINAL DE INFORME'),  # 4 0
                       ('TERMINADO', 'TERMINADO'),  # 5 0
                       ('CANCELADO', 'CANCELADO'))  # 6 0


class Gestor(models.Model):
    user = models.OneToOneField(User)
    numero = models.CharField(max_length=8, help_text="numero de celular")
    server_conection = models.CharField(max_length=25, choices=CONECTIONS,
                                        default='WIFI', null=True, blank=True)
    sms_gateway = models.CharField(max_length=20, null=True)
    foto = models.ImageField(null=True)
    zonas = models.ManyToManyField('Zona', null=True, blank=True)
    tipo_gestion = models.ManyToManyField('TipoGestion', blank=True)
    intervalo = models.PositiveIntegerField(null=True, verbose_name="intervalo de seguimiento",
                                            help_text="esto determina que tan seguido el gestor reportara su posicion gps en segundos")

    def image_thumb(self):
        return '<img src="/media/%s" width="100" height="60" />' % (self.foto)

    image_thumb.allow_tags = True
    image_thumb.short_description = "Imagen"

    def __unicode__(self):
        return str(self.user)

    def to_json(self):
        o = {}
        o['numero'] = self.numero
        o['foto'] = self.foto.url
        o['server_conection'] = self.server_conection
        if self.server_conection == 'SMS + WIFI':
            o['sms_gateway'] = self.sms_gateway
        o['zonas'] = []
        o['tipos_gestion'] = []
        for z in self.zonas.all():
            o['zonas'].append(z.name)
        for t in self.tipo_gestion.all():
            o['tipos_gestion'].append(t.name)
        o['intervalo'] = self.intervalo
        return o

    def full_name(self):
        return "%s %s" % (ifnull(self.user.first_name, self.user.username), ifnull(self.user.last_name, ""))

    class Meta:
        verbose_name = "perito"
        verbose_name_plural = "Peritos"


class Armador(models.Model):
    user = models.OneToOneField(User)
    especialidades = models.ManyToManyField('TipoGestion', blank=True)
    activo = models.BooleanField(default=True)

    def nombres(self):
        return self.user.first_name

    def apellidos(self):
        return self.user.last_name

    def __unicode__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = "armadores"


class Departamento(Entidad):
    pass


class Municipio(Entidad):
    departamento = models.ForeignKey(Departamento)


class Barrio(Entidad):
    municipio = models.ForeignKey(Municipio)

    def referencias(self):
        return Gestion.objects.filter(barrio=self).values_list('direccion', flat=True)[:5]


class Zona(Entidad):
    departamento = models.ForeignKey(Departamento)


class ZonaBarrio(models.Model):
    zona = models.ForeignKey(Zona)
    barrio = models.ForeignKey(Barrio)
    orden = models.IntegerField(null=True, blank=True)


class TipoGestion(Entidad):
    prefijo = models.CharField(max_length=6, null=True, blank=False)
    tiempo_ejecucion = models.IntegerField(null=True, blank=True, verbose_name="tiempo en minutos para el peritaje",
                                           help_text="Tiempo requerido en minutos para el levantamiento de datos de este tipo de avaluo")
    color = ColorField(default="ffffff")
    dias = models.IntegerField(default=4, null=True, verbose_name="dias necesarios para el armado")

    def __unicode__(self):
        return self.name

    def detalles(self):
        return DetalleGestion.objects.filter(tipo_gestion=self)

    def to_json(self):
        obj = {'id': self.id, 'name': self.name}
        obj['campos'] = []
        for d in self.detalles().order_by('orden'):
            obj['campos'].append(d.to_json())
        return obj

    def errores(self):
        errors = ''
        for d in self.detalles():
            if d.error():
                errors += 'El campo %s es de tipo %s, pero no contiene ningun elemento para seleccionar. ' % (
                    d.titulo, d.tipo)
        return errors

    def muestra_color(self):
        return mark_safe('<div style="height: 25px; width: 25px; background-color:%s">' % self.color)

    muestra_color.short_description = "color"

    class Meta:
        verbose_name = "tipo de avaluo"
        verbose_name_plural = "tipos de avaluos"
        ordering = ['prefijo', ]


TIPOS = (
    ('input', 'input'),
    ('radio', 'radio'),
    ('textarea', 'textarea'),
    ('combobox', 'combobox'),
    ('checkbox', 'checkbox'),
    ('foto', 'foto'),
    ('multi foto', 'multi foto'),
    ('firma', 'firma'),
)


class DetalleGestion(models.Model):
    tipo_gestion = models.ForeignKey(TipoGestion)
    tipo = models.CharField(max_length=25, choices=TIPOS, verbose_name="tipo de campo")
    requerido = models.BooleanField(default=True)
    titulo = models.CharField(max_length=65, verbose_name="titulo a mostrar")
    nombreVariable = models.CharField(max_length=65, verbose_name="nombre de la variable")
    habilitado = models.BooleanField(default=True)
    orden = models.IntegerField(null=True, blank=True)
    imprime = models.BooleanField(default=False, verbose_name="se imprime")

    def elementos(self):
        return Elemento.objects.filter(combo=self.id)

    def __unicode__(self):
        return "%s - %s" % (self.tipo_gestion.name, self.nombreVariable)

    def to_json(self):
        o = {}
        o['tipo'] = self.tipo
        o['requerido'] = self.requerido
        o['titulo'] = self.titulo
        o['nombreVariable'] = self.nombreVariable
        o['habilitado'] = self.habilitado
        o['imprime'] = self.imprime
        if self.elementos():
            o['elementos'] = []
        for e in self.elementos():
            o['elementos'].append({'id': e.id, 'valor': e.valor})
        return o

    class Meta:
        verbose_name = "campo"
        verbose_name_plural = "campos requeridos por la gestion"
        ordering = ['orden', ]

    def error(self):
        if (self.tipo == 'combobox' or self.tipo == 'radio') and self.elementos().count() == 0:
            return True
        else:
            return False


class especiales(models.Manager):
    def get_queryset(self):
        return super(especiales, self).get_queryset().filter(tipo__in=['combobox', 'radio'])


class EspecialField(DetalleGestion):
    objects = models.Manager()
    objects = especiales()

    class Meta:
        proxy = True


class Elemento(models.Model):
    combo = models.ForeignKey(EspecialField)
    valor = models.CharField(max_length=65)

    def to_json(self):
        return {'combo': self.combo.id, 'valor': self.valor}


BANCOS = (
    ('BANPRO', 'BANPRO'),
    ('BANCENTRO', 'BANCENTRO'),
    ('BAC', 'BAC'),
    ('BDF', 'BDF'),
    ('FICOHSA', 'FICOHSA'),
    ('PROCREDIT', 'PROCREDIT'),
)


class Gestion_Fin(Entidad):
    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Fines de Avaluo"
        verbose_name = "Finalidad de avaluo"


class Gestion_Uso(Entidad):
    def __unicode__(self):
        return self.name

    fin = models.ForeignKey(Gestion_Fin)

    class Meta:
        verbose_name_plural = "Usos de Avaluo"
        verbose_name = "Uso de avaluo"


class Gestion(models.Model):
    numero = models.CharField(max_length=65, null=True, verbose_name="Número Registro",
                              blank=True,
                              help_text="Numero registro catastro, para el caso de vehiculos el número de chasis")

    factura = models.BooleanField(default=False, verbose_name="Factura")
    fiscal = models.BooleanField(default=False)
    fecha_facturacion = models.DateField(null=True, blank=True)

    cancelada = models.BooleanField(default=False, verbose_name="Cancelada")
    fecha_cancelacion = models.DateField(null=True, blank=True)
    fecha = models.DateField(null=True, blank=True,
                             verbose_name="fecha de solicitud")  # fecha en que se recepciona la solicitud del avaluo

base/views.py
from django.http.response import HttpResponse
from django.forms.models import model_to_dict
from django.db.models import Q
import json
import operator


def find_entidad(sentence, filters=None):
    predicates = []
    if filters:
        predicates = filters
    for word in sentence.split(" "):
        predicates.append(('name__icontains', word))
    return [Q(x) for x in predicates]


def autocomplete_entidad(instance, request, filters=None):
    data = []
    if request.is_ajax:
        model = type(instance)
        result = []
        term = request.GET.get('term', None)
        if term:
            qs = model.objects.filter(reduce(operator.and_, find_entidad(term, filters)))
            for obj in qs:
                obj_json = {}
                obj_json['label'] = obj.name
                obj_json['value'] = obj.name
                obj_json['obj'] = obj.to_json()
                result.append(obj_json)
        data = json.dumps(result)
    return HttpResponse(data, content_type='application/json')


def entidad_to_json(instance, request):
    if request.is_ajax:
        model = type(instance)
        result = []
        id = request.POST.get('id', None)
        obj = model.objects.get(id=id)
        if obj:
            try:
                result = obj.to_json()
            except:
                result = model_to_dict(obj)
            data = json.dumps(result)
    else:
        data = 'fail'
    return HttpResponse(data, content_type='application/json')

dtracking/templates/dtracking/anulacion.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Anulacición cancelación</title>
    <style media="all">
        @page {
            size: a4;
            margin: 2cm;
        }

        table {
            page-break-after: always;
        }

        th {
            color: #409DE0;
            background: #409DE0;
            background-color: #409DE0;
            border: 4px solid #409DE0;
            margin: 1em 5em;
            padding: 1em;
            stroke: none;
            font-variant: normal;
            font-weight: normal;
            font-size: 15px;
            font-family: Calibri;
            -inkscape-font-specification: Calibri;
            writing-mode: lr-tb;
            fill: #ffffff;
            fill-opacity: 1;
            fill-rule: nonzero;
            stroke: none;
        }

        table th {
            padding: .125em;
            margin: 0;
            width: 10%;
            background-color: #FFFFFF;
            border-right: 1px solid #C0C0C0;
            border-top: 1px solid #C0C0C0;
            border-bottom: 1px solid #C0C0C0;
            text-align: center;
            font-size: 15px;
            font-family: Calibri;
            -inkscape-font-specification: Calibri;
            writing-mode: lr-tb;
        }

        .texto {
            font-weight: normal;
            font-style: oblique;
            color: #EEEEEE;
            letter-spacing: 0pt;
            word-spacing: 2pt;
            text-align: center;
            font-family: lucida sans unicode, lucida grande, sans-serif;
            line-height: 1;
            margin: 0px;
            padding: 0px;
        }

        td {
            text-align: center;
        }
    </style>
</head>
<body>
<h1 class="texto" style="font-size:3em;">Se volvio activar el avalúo</h1>
</br>

</body>

dtracking/templates/dtracking/asignacion.html
{% extends "admin/change_form.html" %}

{% block breadcrumbs %}
    <ul class="grp-horizontal-list">
            <li><a href="/admin/">Inicio</a></li>
            <li><a href="/admin/dtracking/gestion/">Volver a Gestiones</a></li>
            <li>Asignacion de {{ total }} Avaluos a Peritos Evaluadores</li>
        </ul>
{% endblock breadcrumbs %}

{% block content %}
    {% if total == 0 %}
        <p>Nada para asignar.</p>
    {% else %}
        {% for obj in queryset %}
            <form onsubmit="return false;">
            {% csrf_token %}
            <input type="hidden" name="gestion" value="{{obj.id}}"/>
            <input readonly type="text" name="descripcion" style="min-width: 300px;" value="{{ obj.destinatario }} - {{ obj.barra }}"/>
            {{ form }}
            <input type="submit" name="asign" value="Asignar" />
            </form>
        {% endfor %}
    {% endif %}
    <script>
    (function($) {
        var asignar = function(){
            var fecha = $(this).parent().find('input[name="fecha_asignacion"]').val().split("/");
            var hora = $(this).parent().find('input[name="hora_asignacion"]').val();
            var data = {'gestion': $(this).parent().find('input[name="gestion"]').val(),
                        'user': $(this).parent().find('select[name="usuario"]').val(),
                        'fecha': fecha[2]+"-"+fecha[1]+"-"+fecha[0] +" "+hora+":00"};
            var gestion = $(this).parent();
            console.log(data);
                $.ajax({
                    url: "/dtracking/asignar_gestion/",
                    method: "POST",
                    data: data,
                    success: function (result) {
                        console.log(result);
                        gestion.remove();
                    },
                    error: function (result) {
                        alert("error");
                        console.log(result);
                    }
                });
            }
        $(document).ready(function(){
            $('input[name="asign"]').on('click', asignar);
        });
    })(grp.jQuery)
    </script>
{% endblock %}

dtracking/templates/dtracking/documentos_adjuntos.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Documentos Ajuntos|{{ obj.barra }}</title>
    <link rel="stylesheet" href="/static/dtracking/css/bootstrap.css" type="text/css">
    <script src="https://use.fontawesome.com/a709970381.js"></script>
</head>
<body>
<div class="">
    <div class="well">
        {% if archivos|length > 0 %}
        <table  class="table table-bordered table-striped table-hover table-responsive">
            <thead>
            <tr>
                <th>Creado por</th>
                <th>Fecha</th>
                <th>Adjunto</th>
                <th>Accion</th>
            </tr>
            </thead>
            <tbody>
            {% for archivo in archivos %}
                <tr>
                    <td>{{ archivo.user }}</td>
                    <td>{{ archivo.fecha }}</td>
                    <td><a href="{{ archivo.archivo.url }}" target="_self"> {{ archivo.archivo.name }}</a> </td>
                    <td><button onclick="borrar({{ archivo.pk }})" class="btn btn-danger"><i class="fa fa-trash"></i></button></td>
                </tr>

            {% endfor %}
            </tbody>
        </table>
        {% else %}
        <div class="alert alert-info">No hay Adjuntos</div>
        {% endif %}

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="hidden" name="pk_gestion" value="{{ pk_gestion }}">
            <div class="input-group">
              <input type="file" name="archivo" class="form-control">
            </div>
            <button type="submit" class="btn btn-primary"><i class="fa fa-cloud-upload"></i> Subir adjunto</button>
        </form>
    </div>

</div>
<script type="text/javascript" src="/static/home/js/jquery.js"></script>
<script type="text/javascript" src="/static/dtracking/js/FileSaver.js"></script>
<script type="text/javascript" src="/static/dtracking/js/jquery.wordexport.js"></script>
<script type="text/javascript" src="/static/dtracking/js/jquery.googoose.js"></script>

<script>
    function borrar(id) {
        var r = confirm("Desea realmente borrar este adjunto?");
        if  (r === true) {
            var data = {id:id};
            $.ajax({
                url : '{% url 'gestion_borrar_adjunto' %}',
                type : 'POST',
                data : data,
                success : function(response){
                    if(response.code===200){
                        window.location.reload();
                    }else{
                        alert(response.mensaje);
                    }
                }
            });
        }

    }
</script>
</body>
</html>

dtracking/templates/dtracking/gestion.html
{% extends "admin/change_form.html" %}
{% load i18n admin_urls static admin_modify %}
{% block object-tools %}
    <ul class="grp-object-tools">
        {% block object-tools-items %}
            {% if has_add_permission %}
                {% if original.terminada %}
                    <li>
                        <a id="adjuntos" href="#" class="addlink show_atachments"
                           data-url="{% url "gestion_adjuntos" %}?pk={{ original.pk }}"
                           data-name="Documentos Adjuntos">
                            Generar Prefactura
                        </a>
                    </li>
                {% endif %}
                <li>
                    <a id="adjuntos" href="#" class="addlink show_atachments"
                       data-url="{% url "gestion_adjuntos" %}?pk={{ original.pk }}"
                       data-name="Documentos Adjuntos">
                        Documentos Adjuntos
                    </a>
                </li>
                <li>
                    <a id="proforma" href="#" class="addlink show_atachments"
                       data-url="{% url "generar_asignacion" %}?documento={{ original.pk }}"
                       data-name="Generar Ficha">
                        Generar Ficha
                    </a>
                </li>
                <li>
                    <a id="ficha" href="#" class="addlink show_atachments"
                       data-url="{% url "gestion_proforma" %}?gestion={{ original.pk }}"
                       data-name="Generar Proforma">
                        Generar Cotizacion
                    </a>
                </li>
                {% if  original.cancelada %}
                    <li><a class="object-execute" data-method="restablecer"
                           data-app-label="{{ opts.app_label }}"
                           data-model-name="{{ opts.model_name }}"
                           data-id="{{ original.id }}">Restablecer</a></li>
                {% endif %}
            {% endif %}
            {{ block.super }}
        {% endblock %}
    </ul>
{% endblock %}

{% block extrahead %}
    <script type="text/javascript" src="/static/home/js/jquery.min.js"></script>
    <link rel="stylesheet" href='{% static 'izimodal/css/iziModal.min.css' %}' type="text/css">
    <script type="text/javascript" src='{% static 'izimodal/js/iziModal.min.js' %}'></script>
    <script type="text/javascript">
        (function ($) {
            $(document).ready(function () {
                $("#id_categoria").prop("disabled", true);

                if (String($('#id_municipio').val()).length === 0)
                    $('#id_municipio').empty();
                if (String($('#id_barrio').val()).length === 0)
                    $('#id_barrio').empty();
                if (String($('#id_uso_gestion').val()).length === 0)
                    $('#id_uso_gestion').empty();

                var cargar_municipios = function () {
                    $.ajax('/dtracking/get_municipios/',
                        {
                            type: 'POST',
                            data: {'departamento': $(this).val()},
                            success: function (result) {
                                $('#id_municipio').empty();
                                $('#id_municipio').append('<option value=""> ---- </option>');
                                $.each(result, function (i, o) {
                                    $('#id_municipio').append("<option value=" + o.id + ">" + o.name + "</option>");
                                });
                            }
                        });
                };
                $('#id_departamento').on('change', cargar_municipios);

                var cargar_barrios = function () {
                    $.ajax('/dtracking/get_barrios/',
                        {
                            type: 'POST',
                            data: {'municipio': $(this).val()},
                            success: function (result) {
                                $('#id_barrio').empty();
                                $('#id_barrio').append('<option value=""> ---- </option>');
                                $.each(result, function (i, o) {
                                    $('#id_barrio').append("<option value=" + o.id + ">" + o.name + "</option>");
                                });
                            }
                        });
                };
                $('#id_municipio').on('change', cargar_barrios);

                var cargar_usos_gestion = function () {
                    $.ajax('/dtracking/get_usos_gestion/',
                        {
                            type: 'POST',
                            data: {'fin': $(this).val()},
                            success: function (result) {
                                $('#id_uso_gestion').empty();
                                $('#id_uso_gestion').append('<option value=""> ---- </option>');
                                $.each(result, function (i, o) {
                                    $('#id_uso_gestion').append("<option value=" + o.id + ">" + o.name + "</option>");
                                });
                            }
                        });
                };
                $('#id_fin_gestion').on('change', cargar_usos_gestion);


                var cargar_ejecutivos = function () {
                    $.ajax('/admin/ajax/get_collection/',
                        {
                            type: 'POST',
                            data: {
                                'app_label': 'dtracking',
                                'model': 'ejecutivo',
                                'filters': "{'banco': " + $(this).val() + "}"
                            },
                            success: function (result) {
                                $('#id_new_ejecutivo').empty();
                                $('#id_new_ejecutivo').append('<option value=""> ---- </option>');
                                $.each(result, function (i, o) {
                                    $('#id_new_ejecutivo').append("<option value=" + o.id + ">" + o.nombre + "</option>");
                                });
                            }
                        });
                };
                $('#id_new_banco').on('change', cargar_ejecutivos);

                var calcular_categoria = function () {
                    monto = $(this).val();
                    var categoria = "Cat. 1";
                    if (monto >= 101 && monto <= 200) {
                        categoria = "Cat. 2";
                    }
                    if (monto >= 201 && monto <= 500) {
                        categoria = "Cat. 3";
                    }
                    if (monto >= 501 && monto <= 1000) {
                        categoria = "Cat. 4";
                    }
                    if (monto > 1000) {
                        categoria = "Cat. 5";
                    }

                    console.log(categoria);
                    $("#id_categoria").val(categoria);
                };

                $('#id_valor').on('change', calcular_categoria);

                var atachments_info = function () {
                    window.open(
                        $(this).data('url'),
                        $(this).data('name'),
                        "width=600mm, height=500mm,  status=no, menubar=no, location=no");
                };

                $('.show_atachments').on('click', atachments_info);

                var execute = function () {
                    $.ajax('{% url 'ajax_objectExecute' %}', {
                        method: 'post',
                        data: {
                            app_label: $(this).data('app-label'),
                            model: $(this).data('model-name'),
                            id: $(this).data('id'),
                            method: $(this).data('method')
                        },
                        success: function (o) {
                            location.reload();
                        }
                    })
                }
                $(".object-execute").on("click", execute);

            });
        })(grp.jQuery)

    </script>
{% endblock %}